name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  # 최신 버전 사용

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # 최신 버전 사용
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: Log Node.js version
      run: node --version  # 사용 중인 Node.js 버전 확인

    - name: Build Docker image
      run: |
        docker build -t your-docker-image:latest .

    - name: Display success message
      run: echo "Docker image built successfully!"
