name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'  # 'temurin' 또는 다른 배포판 사용 가능

    - name: Build Docker image
      run: |
        docker build -t your-docker-image:latest .

    - name: Display success message
      run: echo "Docker image built successfully!"
